"""Python equivalent of `IFFT_FFT _ODFM.m`.

This deterministic experiment generates one 64-subcarrier QPSK OFDM symbol,
adds a 16-sample cyclic prefix, removes it at the ideal receiver, applies the
FFT, and checks symbol/bit recovery. Two publication-ready PNG figures and a
text result file are written to the project directories.

Requirements: numpy, matplotlib
Run from any directory:
    python code/ifft_fft_ofdm.py
"""
from __future__ import annotations

from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "figures"
GEN_DIR = ROOT / "generated_figures"
FIG_DIR.mkdir(exist_ok=True)
GEN_DIR.mkdir(exist_ok=True)


def qpsk_modulate(bits: np.ndarray) -> np.ndarray:
    """Map bit pairs using 00->(-1-j)/sqrt(2), ..., 11->(1+j)/sqrt(2)."""
    bits = np.asarray(bits, dtype=np.int8).reshape(-1)
    if bits.size % 2:
        raise ValueError("QPSK modulation requires an even number of bits")
    pairs = bits.reshape(-1, 2)
    in_phase = 2 * pairs[:, 0] - 1
    quadrature = 2 * pairs[:, 1] - 1
    return (in_phase + 1j * quadrature) / np.sqrt(2.0)


def qpsk_hard_demodulate(symbols: np.ndarray) -> np.ndarray:
    """Hard-decision QPSK demodulator matched to qpsk_modulate()."""
    pairs = np.column_stack((symbols.real >= 0.0, symbols.imag >= 0.0))
    return pairs.astype(np.int8).reshape(-1)


def run_ofdm_loopback(seed: int = 1, n_subcarriers: int = 64, cp_length: int = 16):
    if n_subcarriers <= 0 or cp_length < 0 or cp_length > n_subcarriers:
        raise ValueError("Invalid OFDM parameters")

    rng = np.random.default_rng(seed)
    tx_bits = rng.integers(0, 2, size=2 * n_subcarriers, dtype=np.int8)
    frequency_symbols = qpsk_modulate(tx_bits)

    time_symbol = np.fft.ifft(frequency_symbols, n=n_subcarriers)
    cyclic_prefix = time_symbol[-cp_length:] if cp_length else np.empty(0, complex)
    tx_signal = np.concatenate((cyclic_prefix, time_symbol))

    # Ideal channel, matching the supplied MATLAB experiment.
    rx_signal = tx_signal.copy()
    rx_without_cp = rx_signal[cp_length : cp_length + n_subcarriers]
    recovered_symbols = np.fft.fft(rx_without_cp, n=n_subcarriers)
    rx_bits = qpsk_hard_demodulate(recovered_symbols)

    symbol_error = recovered_symbols - frequency_symbols
    max_abs_error = float(np.max(np.abs(symbol_error)))
    bit_errors = int(np.count_nonzero(tx_bits != rx_bits))
    ber = bit_errors / tx_bits.size

    return {
        "tx_bits": tx_bits,
        "frequency_symbols": frequency_symbols,
        "time_symbol": time_symbol,
        "tx_signal": tx_signal,
        "recovered_symbols": recovered_symbols,
        "rx_bits": rx_bits,
        "symbol_error": symbol_error,
        "max_abs_error": max_abs_error,
        "bit_errors": bit_errors,
        "ber": ber,
        "n_subcarriers": n_subcarriers,
        "cp_length": cp_length,
        "seed": seed,
    }


def plot_ifft_generation(result: dict) -> Path:
    n = result["n_subcarriers"]
    cp = result["cp_length"]
    x_freq = result["frequency_symbols"]
    x_time = result["time_symbol"]
    tx = result["tx_signal"]

    fig, axes = plt.subplots(2, 2, figsize=(10.2, 7.0))

    axes[0, 0].scatter(x_freq.real, x_freq.imag, facecolors="none", edgecolors="black")
    axes[0, 0].set_aspect("equal", adjustable="box")
    axes[0, 0].set_xlim(-1.5, 1.5)
    axes[0, 0].set_ylim(-1.5, 1.5)
    axes[0, 0].set_xlabel("In-phase")
    axes[0, 0].set_ylabel("Quadrature")
    axes[0, 0].set_title("Transmitted QPSK Symbols")

    markerline, stemlines, baseline = axes[0, 1].stem(np.arange(n), np.abs(x_freq), basefmt=" ")
    plt.setp(markerline, markerfacecolor="white", markeredgecolor="black")
    plt.setp(stemlines, color="black")
    axes[0, 1].set_xlabel("Subcarrier index k")
    axes[0, 1].set_ylabel("|X[k]|")
    axes[0, 1].set_title("Frequency-Domain Data")

    axes[1, 0].plot(np.arange(n), x_time.real, color="black", label="Real part")
    axes[1, 0].plot(np.arange(n), x_time.imag, color="black", linestyle="--", label="Imaginary part")
    axes[1, 0].set_xlabel("Sample index n")
    axes[1, 0].set_ylabel("Amplitude")
    axes[1, 0].set_title("OFDM Symbol Generated by IFFT")
    axes[1, 0].legend()

    axes[1, 1].plot(np.arange(tx.size), np.abs(tx), color="black", label="|x_CP[n]|")
    axes[1, 1].axvline(cp - 0.5, color="black", linestyle="--", label="End of cyclic prefix")
    axes[1, 1].set_xlabel("Sample index n")
    axes[1, 1].set_ylabel("Magnitude")
    axes[1, 1].set_title("OFDM Symbol with Cyclic Prefix")
    axes[1, 1].legend()

    for ax in axes.flat:
        ax.grid(True, alpha=0.3)

    fig.tight_layout()
    output = FIG_DIR / "sim1_ifft_ofdm_python.png"
    fig.savefig(output, dpi=300, bbox_inches="tight")
    fig.savefig(GEN_DIR / output.name, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return output


def plot_fft_recovery(result: dict) -> Path:
    n = result["n_subcarriers"]
    tx_symbols = result["frequency_symbols"]
    rx_symbols = result["recovered_symbols"]
    error = result["symbol_error"]
    tx_bits = result["tx_bits"]
    rx_bits = result["rx_bits"]

    fig, axes = plt.subplots(2, 2, figsize=(10.2, 7.0))

    axes[0, 0].scatter(tx_symbols.real, tx_symbols.imag, facecolors="none", edgecolors="black", label="Original")
    axes[0, 0].scatter(rx_symbols.real, rx_symbols.imag, marker="x", color="black", label="Recovered")
    axes[0, 0].set_aspect("equal", adjustable="box")
    axes[0, 0].set_xlim(-1.5, 1.5)
    axes[0, 0].set_ylim(-1.5, 1.5)
    axes[0, 0].set_xlabel("In-phase")
    axes[0, 0].set_ylabel("Quadrature")
    axes[0, 0].set_title("Original and Recovered QPSK Symbols")
    axes[0, 0].legend()

    k = np.arange(n)
    axes[0, 1].plot(k, np.abs(tx_symbols), color="black", drawstyle="steps-mid", label="Original")
    axes[0, 1].plot(k, np.abs(rx_symbols), color="black", linestyle="--", drawstyle="steps-mid", label="Recovered")
    axes[0, 1].set_xlabel("Subcarrier index k")
    axes[0, 1].set_ylabel("Magnitude")
    axes[0, 1].set_title("Original and Recovered Spectra")
    axes[0, 1].legend()

    markerline, stemlines, baseline = axes[1, 0].stem(k, np.abs(error), basefmt=" ")
    plt.setp(markerline, markerfacecolor="white", markeredgecolor="black")
    plt.setp(stemlines, color="black")
    axes[1, 0].set_xlabel("Subcarrier index k")
    axes[1, 0].set_ylabel("|X_r[k]-X[k]|")
    axes[1, 0].set_title("Absolute Recovery Error")
    axes[1, 0].set_yscale("log")

    count = min(32, tx_bits.size)
    bit_index = np.arange(count)
    axes[1, 1].step(bit_index, tx_bits[:count], where="post", color="black", label="Transmitted bits")
    axes[1, 1].step(bit_index, rx_bits[:count], where="post", color="black", linestyle="--", label="Recovered bits")
    axes[1, 1].set_ylim(-0.2, 1.2)
    axes[1, 1].set_xlabel("Bit index")
    axes[1, 1].set_ylabel("Bit value")
    axes[1, 1].set_title("First 32 Transmitted and Recovered Bits")
    axes[1, 1].legend()

    for ax in axes.flat:
        ax.grid(True, alpha=0.3)

    fig.suptitle(
        f"Ideal OFDM Loopback: max FFT error = {result['max_abs_error']:.3e}, "
        f"BER = {result['ber']:.1e}"
    )
    fig.tight_layout()
    output = FIG_DIR / "sim2_fft_recovery_python.png"
    fig.savefig(output, dpi=300, bbox_inches="tight")
    fig.savefig(GEN_DIR / output.name, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return output



def plot_publication_summary(result: dict) -> Path:
    """Create a compact four-panel figure suitable for one IEEE column."""
    n = result["n_subcarriers"]
    cp = result["cp_length"]
    tx_symbols = result["frequency_symbols"]
    rx_symbols = result["recovered_symbols"]
    time_symbol = result["time_symbol"]
    tx_signal = result["tx_signal"]
    error = np.abs(result["symbol_error"])
    tx_bits = result["tx_bits"]
    rx_bits = result["rx_bits"]

    fig, axes = plt.subplots(2, 2, figsize=(7.2, 6.2))

    axes[0, 0].scatter(tx_symbols.real, tx_symbols.imag, facecolors="none", edgecolors="black", label="TX")
    axes[0, 0].scatter(rx_symbols.real, rx_symbols.imag, marker="x", color="black", label="RX")
    axes[0, 0].set_aspect("equal", adjustable="box")
    axes[0, 0].set_xlim(-1.25, 1.25)
    axes[0, 0].set_ylim(-1.25, 1.25)
    axes[0, 0].set_xlabel("In-phase")
    axes[0, 0].set_ylabel("Quadrature")
    axes[0, 0].set_title("QPSK Constellation")
    axes[0, 0].legend(fontsize=8)

    axes[0, 1].plot(np.arange(n), time_symbol.real, color="black", label="Real")
    axes[0, 1].plot(np.arange(n), time_symbol.imag, color="black", linestyle="--", label="Imag.")
    axes[0, 1].set_xlabel("IFFT sample n")
    axes[0, 1].set_ylabel("Amplitude")
    axes[0, 1].set_title("64-Point IFFT Output")
    axes[0, 1].legend(fontsize=8)

    axes[1, 0].plot(np.arange(tx_signal.size), np.abs(tx_signal), color="black")
    axes[1, 0].axvline(cp - 0.5, color="black", linestyle="--")
    axes[1, 0].annotate("CP boundary", xy=(cp - 0.5, np.max(np.abs(tx_signal)) * 0.75),
                        xytext=(cp + 5, np.max(np.abs(tx_signal)) * 0.95),
                        arrowprops={"arrowstyle": "->", "color": "black"}, fontsize=8)
    axes[1, 0].set_xlabel("Transmitted sample n")
    axes[1, 0].set_ylabel("Magnitude")
    axes[1, 0].set_title("Cyclic Prefix Insertion")

    count = min(32, tx_bits.size)
    bit_index = np.arange(count)
    axes[1, 1].step(bit_index, tx_bits[:count], where="post", color="black", label="TX bits")
    axes[1, 1].step(bit_index, rx_bits[:count], where="post", color="black", linestyle="--", label="RX bits")
    axes[1, 1].set_ylim(-0.2, 1.2)
    axes[1, 1].set_xlabel("Bit index")
    axes[1, 1].set_ylabel("Bit value")
    axes[1, 1].set_title(f"Recovery: BER=0, max error={result['max_abs_error']:.1e}")
    axes[1, 1].legend(fontsize=8)

    for ax in axes.flat:
        ax.grid(True, alpha=0.3)

    fig.tight_layout()
    output = FIG_DIR / "ofdm_loopback_summary_python.png"
    fig.savefig(output, dpi=300, bbox_inches="tight")
    fig.savefig(GEN_DIR / output.name, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return output

def main() -> None:
    result = run_ofdm_loopback()
    fig1 = plot_ifft_generation(result)
    fig2 = plot_fft_recovery(result)
    fig3 = plot_publication_summary(result)

    report = (
        "PYTHON OFDM IFFT/FFT LOOPBACK\n"
        f"Seed: {result['seed']}\n"
        f"Number of subcarriers: {result['n_subcarriers']}\n"
        f"Cyclic-prefix length: {result['cp_length']} samples\n"
        f"Transmitted signal length: {result['tx_signal'].size} samples\n"
        f"Maximum absolute FFT recovery error: {result['max_abs_error']:.16e}\n"
        f"Number of bit errors: {result['bit_errors']}/{result['tx_bits'].size}\n"
        f"Bit error rate: {result['ber']:.16e}\n"
        f"Figures: {fig1.name}, {fig2.name}, {fig3.name}\n"
    )
    (ROOT / "ofdm_python_results.txt").write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
