%% SIMPLE OFDM SIMULATION USING IFFT AND FFT
% Simulation 1: IFFT generates an OFDM signal
% Simulation 2: FFT recovers the transmitted QPSK data
% No additional MATLAB toolbox is required.

clc;
clear;
close all;

rng(1);                    % Reproducible random data

%% System parameters
N = 64;                    % Number of OFDM subcarriers
Ncp = 16;                  % Cyclic-prefix length
numberOfBits = 2 * N;      % QPSK uses two bits per subcarrier

%% Generate random input bits
txBits = randi([0 1], numberOfBits, 1);
bitPairs = reshape(txBits, 2, []).';

%% QPSK modulation
% 00 -> (-1-j)/sqrt(2)
% 01 -> (-1+j)/sqrt(2)
% 10 -> ( 1-j)/sqrt(2)
% 11 -> ( 1+j)/sqrt(2)

inPhase = 2 * bitPairs(:,1) - 1;
quadrature = 2 * bitPairs(:,2) - 1;

X = (inPhase + 1j * quadrature) / sqrt(2);

%% ==============================================================
%  SIMULATION 1: IFFT GENERATES THE OFDM TIME-DOMAIN SIGNAL
% ===============================================================

% Convert frequency-domain QPSK symbols to an OFDM signal
x = ifft(X, N);

% Add the cyclic prefix
cyclicPrefix = x(end-Ncp+1:end);
txSignal = [cyclicPrefix; x];

fprintf('SIMULATION 1: IFFT GENERATES THE OFDM SIGNAL\n');
fprintf('Number of subcarriers       : %d\n', N);
fprintf('Cyclic-prefix length        : %d samples\n', Ncp);
fprintf('Transmitted signal length   : %d samples\n\n', ...
        length(txSignal));

figure('Name', 'Simulation 1: IFFT Generates OFDM Signal', ...
       'Color', 'w');

subplot(2,2,1);
plot(real(X), imag(X), 'bo', ...
     'MarkerFaceColor', 'b', ...
     'MarkerSize', 6);
grid on;
axis equal;
xlim([-1.5 1.5]);
ylim([-1.5 1.5]);
xlabel('In-phase');
ylabel('Quadrature');
title('Transmitted QPSK Symbols');

subplot(2,2,2);
stem(0:N-1, abs(X), 'filled');
grid on;
xlabel('Subcarrier Index k');
ylabel('|X(k)|');
title('Frequency-Domain Data');

subplot(2,2,3);
plot(0:N-1, real(x), 'b', 'LineWidth', 1.1);
hold on;
plot(0:N-1, imag(x), 'r--', 'LineWidth', 1.1);
grid on;
xlabel('Sample Index n');
ylabel('Amplitude');
title('OFDM Signal Generated by IFFT');
legend('Real Part', 'Imaginary Part', ...
       'Location', 'best');

subplot(2,2,4);
plot(0:length(txSignal)-1, abs(txSignal), ...
     'k', 'LineWidth', 1.1);
hold on;
xline(Ncp-0.5, 'r--', 'LineWidth', 1.2);
grid on;
xlabel('Sample Index n');
ylabel('Magnitude');
title('OFDM Signal with Cyclic Prefix');
legend('|x_{CP}(n)|', 'End of Cyclic Prefix', ...
       'Location', 'best');

print(gcf, 'sim1_ifft_ofdm.png', '-dpng', '-r300');

%% ==============================================================
%  SIMULATION 2: FFT RECOVERS THE TRANSMITTED DATA
% ===============================================================

% Ideal channel: the received signal equals the transmitted signal
rxSignal = txSignal;

% Remove the cyclic prefix
rxWithoutCP = rxSignal(Ncp+1:Ncp+N);

% Recover the frequency-domain QPSK symbols
XRecovered = fft(rxWithoutCP, N);

%% QPSK hard-decision demodulation
rxBitPairs = zeros(N, 2);
rxBitPairs(:,1) = real(XRecovered) >= 0;
rxBitPairs(:,2) = imag(XRecovered) >= 0;
rxBits = reshape(rxBitPairs.', [], 1);

%% Calculate recovery performance
symbolError = XRecovered - X;
maximumAbsoluteError = max(abs(symbolError));

numberOfBitErrors = sum(txBits ~= rxBits);
bitErrorRate = numberOfBitErrors / numberOfBits;

fprintf('SIMULATION 2: FFT RECOVERS THE TRANSMITTED DATA\n');
fprintf('Maximum absolute FFT error : %.3e\n', ...
        maximumAbsoluteError);
fprintf('Number of bit errors       : %d/%d\n', ...
        numberOfBitErrors, numberOfBits);
fprintf('Bit error rate             : %.6f\n', bitErrorRate);

figure('Name', 'Simulation 2: FFT Recovers QPSK Data', ...
       'Color', 'w');

subplot(2,2,1);
plot(real(X), imag(X), 'bo', ...
     'MarkerSize', 9, ...
     'LineWidth', 1.2);
hold on;
plot(real(XRecovered), imag(XRecovered), 'rx', ...
     'MarkerSize', 7, ...
     'LineWidth', 1.5);
grid on;
axis equal;
xlim([-1.5 1.5]);
ylim([-1.5 1.5]);
xlabel('In-phase');
ylabel('Quadrature');
title('Original and Recovered QPSK Symbols');
legend('Original', 'Recovered', ...
       'Location', 'best');

subplot(2,2,2);
stem(0:N-1, abs(X), 'b', ...
     'LineWidth', 1.0);
hold on;
stem(0:N-1, abs(XRecovered), 'r--', ...
     'LineWidth', 1.0);
grid on;
xlabel('Subcarrier Index k');
ylabel('Magnitude');
title('Original and Recovered Spectra');
legend('Original', 'Recovered', ...
       'Location', 'best');

subplot(2,2,3);
stem(0:N-1, abs(symbolError), 'filled');
grid on;
xlabel('Subcarrier Index k');
ylabel('|X_r(k)-X(k)|');
title('Absolute Recovery Error');

subplot(2,2,4);
stairs(0:min(31,numberOfBits-1), ...
       txBits(1:min(32,numberOfBits)), ...
       'b', 'LineWidth', 1.2);
hold on;
stairs(0:min(31,numberOfBits-1), ...
       rxBits(1:min(32,numberOfBits)), ...
       'r--', 'LineWidth', 1.2);
grid on;
ylim([-0.2 1.2]);
xlabel('Bit Index');
ylabel('Bit Value');
title('First 32 Transmitted and Recovered Bits');
legend('Transmitted Bits', 'Recovered Bits', ...
       'Location', 'best');

print(gcf, 'sim2_fft_recovery.png', '-dpng', '-r300');