#!/usr/bin/env python3
"""Generate LaTeX result macros only from the machine-readable manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "reports" / "results_manifest.json"
OUTPUT_PATH = ROOT / "paper" / "generated" / "results_macros.tex"


def grouped(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def tex_text(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
    }
    return "".join(replacements.get(char, char) for char in value)


def get(mapping: dict[str, Any], *path: str, default: Any = None) -> Any:
    current: Any = mapping
    for key in path:
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current


def macro(name: str, value: str) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def render(manifest: dict[str, Any], require_vivado: bool) -> str:
    fixed = manifest["fixed_point"]
    reference = manifest.get("independent_rtl_crosscheck") or {}
    vivado = manifest["vivado"]
    completed = vivado.get("status") == "completed"
    if require_vivado and not completed:
        raise ValueError("Vivado results are incomplete")

    behavioral = vivado.get("behavioral_simulation", reference)
    source_label = (
        "Xilinx Vivado Simulator (XSim)"
        if completed
        else "independent CXXRTL pre-check"
    )
    status_label = "COMPLETED" if completed else "NOT EXECUTED"
    version = str(get(vivado, "metadata", "vivado_version", default="not recorded"))
    target = str(get(vivado, "metadata", "target_part", default="xc7a35tcpg236-1"))
    period = float(get(vivado, "metadata", "target_period_ns", default=25.0))
    ofdm = manifest["ofdm_integration"]
    sweep_by_width = {
        int(row["width_bits"]): row for row in fixed["word_length_sweep"]
    }
    sweep16 = sweep_by_width[16]

    lines = [
        "% Auto-generated by scripts/generate_paper_macros.py.",
        "% Do not hand-edit numerical results in paper/main.tex.",
        r"\newif\ifVivadoCompleted",
        r"\VivadoCompletedtrue" if completed else r"\VivadoCompletedfalse",
        macro("VivadoStatus", tex_text(status_label)),
        macro("VivadoVersion", tex_text(version)),
        macro("TargetPart", tex_text(target.upper())),
        macro("TargetPeriodNs", f"{period:.3f}"),
        macro("TargetClockMHz", f"{1000.0 / period:.2f}"),
        macro("RtlEvidenceSource", tex_text(source_label)),
        macro("RtlFrames", grouped(int(behavioral.get("frames", 0)))),
        macro("RtlOutputs", grouped(int(behavioral.get("outputs_checked", 0)))),
        macro("RtlMismatches", grouped(int(behavioral.get("mismatches", 0)))),
        macro(
            "RtlAssertions",
            grouped(int(behavioral.get("assertion_failures", 0))),
        ),
        macro(
            "RtlOverflowFrames",
            grouped(int(behavioral.get("overflow_frames", 0))),
        ),
        macro(
            "LatencyFirst",
            str(int(behavioral.get("latency_start_to_first_output_cycles", 0))),
        ),
        macro(
            "LatencyDone",
            str(int(behavioral.get("latency_start_to_done_cycles", 0))),
        ),
        macro("InitiationInterval", "29"),
        macro("DirectedFrames", "11"),
        macro("RandomFrames", grouped(1998)),
        macro("OfdmFrames", grouped(int(ofdm["frames"]))),
        macro("OfdmBits", grouped(int(ofdm["total_bits"]))),
        macro("OfdmBitErrors", grouped(int(ofdm["bit_errors"]))),
        macro("OfdmBer", f"{float(ofdm['ber']):.3g}"),
        macro(
            "OfdmEvmPercent",
            f"{float(ofdm['rms_evm_percent_after_rx_gain_compensation']):.4f}",
        ),
        macro(
            "OfdmMaxError",
            f"{float(ofdm['maximum_complex_error_after_rx_gain_compensation']):.3e}",
        ),
        macro("OfdmCpLength", str(int(ofdm["cyclic_prefix_samples"]))),
        macro(
            "OfdmReceiverPayloadMbps",
            f"{16.0 * (1000.0 / period) / 29.0:.3f}",
        ),
        macro(
            "OfdmSharedPayloadMbps",
            f"{16.0 * (1000.0 / period) / (2.0 * 29.0):.3f}",
        ),
        macro("MetricFrames", grouped(int(sweep16["frames"]))),
        macro("TwiddleCoefficient", str(fixed["format"]["coefficient"])),
        macro("TwiddleCoefficientHex", fixed["format"]["coefficient_hex"]),
        macro(
            "StageCyclesTotal",
            grouped(int(behavioral.get("stage0_cycles", 0))),
        ),
        macro(
            "TwiddleZeroUses",
            grouped(int(behavioral.get("twiddle_W0_uses", 0))),
        ),
        macro(
            "TwiddleOneUses",
            grouped(int(behavioral.get("twiddle_W1_uses", 0))),
        ),
        macro(
            "TwiddleTwoUses",
            grouped(int(behavioral.get("twiddle_W2_uses", 0))),
        ),
        macro(
            "TwiddleThreeUses",
            grouped(int(behavioral.get("twiddle_W3_uses", 0))),
        ),
    ]

    width_words = {
        8: "Eight",
        10: "Ten",
        12: "Twelve",
        14: "Fourteen",
        16: "Sixteen",
    }
    for width, word in width_words.items():
        row = sweep_by_width[width]
        lines.extend(
            [
                macro(f"Sqnr{word}", f"{float(row['sqnr_db']):.2f}"),
                macro(f"Evm{word}", f"{float(row['rms_evm_percent']):.4f}"),
                macro(
                    f"MaxError{word}",
                    f"{float(row['maximum_complex_error']):.3e}",
                ),
                macro(f"Saturations{word}", grouped(int(row["saturations"]))),
            ]
        )

    transistor = manifest.get("transistor_level") or {}
    full_adder = transistor.get("full_adder", {})
    ripple = transistor.get("ripple19", {})
    reference_mapping = manifest.get("reference_xilinx_mapping") or {}
    mapping_baseline = reference_mapping.get("baseline", {})
    mapping_optimized = reference_mapping.get("optimized", {})
    lines.extend(
        [
            macro(
                "ReferenceMappingTool",
                tex_text(
                    f"{reference_mapping.get('tool', 'not recorded')} "
                    f"{reference_mapping.get('version', '')}".strip()
                ),
            ),
            macro(
                "ReferenceBaselineLuts",
                grouped(int(mapping_baseline.get("mapped_lut_primitives", 0))),
            ),
            macro(
                "ReferenceOptimizedLuts",
                grouped(int(mapping_optimized.get("mapped_lut_primitives", 0))),
            ),
            macro(
                "ReferenceBaselineRegisters",
                grouped(int(mapping_baseline.get("register_primitives", 0))),
            ),
            macro(
                "ReferenceOptimizedRegisters",
                grouped(int(mapping_optimized.get("register_primitives", 0))),
            ),
            macro(
                "ReferenceBaselineCarry",
                grouped(int(mapping_baseline.get("carry4_primitives", 0))),
            ),
            macro(
                "ReferenceOptimizedCarry",
                grouped(int(mapping_optimized.get("carry4_primitives", 0))),
            ),
            macro(
                "ReferenceBaselineDsps",
                grouped(int(mapping_baseline.get("dsp48e1_primitives", 0))),
            ),
            macro(
                "ReferenceOptimizedDsps",
                grouped(int(mapping_optimized.get("dsp48e1_primitives", 0))),
            ),
            macro(
                "ReferenceBaselineMuxfSeven",
                grouped(int(mapping_baseline.get("muxf7_primitives", 0))),
            ),
            macro(
                "ReferenceOptimizedMuxfSeven",
                grouped(int(mapping_optimized.get("muxf7_primitives", 0))),
            ),
            macro(
                "FullAdderTransistors",
                grouped(int(full_adder.get("transistor_count", 0))),
            ),
            macro(
                "FullAdderFailures",
                grouped(int(full_adder.get("truth_table_failures", 0))),
            ),
            macro(
                "RippleTransistors",
                grouped(int(ripple.get("transistor_count", 0))),
            ),
            macro(
                "CarryRiseNs",
                f"{float(ripple.get('carry_rise_delay_s', 0.0)) * 1e9:.3f}",
            ),
            macro(
                "CarryFallNs",
                f"{float(ripple.get('carry_fall_delay_s', 0.0)) * 1e9:.3f}",
            ),
            macro(
                "CarryWorstNs",
                f"{float(ripple.get('worst_carry_delay_s', 0.0)) * 1e9:.3f}",
            ),
            macro(
                "CarryPowerMicroW",
                f"{float(ripple.get('average_test_power_w', 0.0)) * 1e6:.2f}",
            ),
            macro(
                "CarryEnergyPj",
                f"{float(ripple.get('transition_window_energy_j', 0.0)) * 1e12:.3f}",
            ),
        ]
    )

    if completed:
        synth = vivado["synthesis"]["optimized_utilization"]
        baseline = vivado["synthesis"]["baseline_utilization"]
        impl = vivado["implementation"]
        util = impl["utilization"]
        timing = impl["timing"]
        power = impl["power"]
        power_source = str(
            get(power, "provenance", "activity_source", default="not recorded")
        )
        derived = impl.get("derived", {})

        def used(resource: dict[str, Any]) -> int:
            return int(resource.get("used", 0))

        def available(resource: dict[str, Any]) -> int:
            return int(resource.get("available", 0))

        lines.extend(
            [
                macro("SynthLuts", grouped(used(synth["slice_luts"]))),
                macro("SynthRegisters", grouped(used(synth["slice_registers"]))),
                macro("SynthDsps", grouped(used(synth["dsps"]))),
                macro("SynthBrams", grouped(used(synth["block_ram_tiles"]))),
                macro("BaselineSynthLuts", grouped(used(baseline["slice_luts"]))),
                macro(
                    "BaselineSynthRegisters",
                    grouped(used(baseline["slice_registers"])),
                ),
                macro("BaselineSynthDsps", grouped(used(baseline["dsps"]))),
                macro(
                    "BaselineSynthBrams",
                    grouped(used(baseline["block_ram_tiles"])),
                ),
                macro("ImplLuts", grouped(used(util["slice_luts"]))),
                macro("ImplLutsAvailable", grouped(available(util["slice_luts"]))),
                macro("ImplRegisters", grouped(used(util["slice_registers"]))),
                macro(
                    "ImplRegistersAvailable",
                    grouped(available(util["slice_registers"])),
                ),
                macro("ImplDsps", grouped(used(util["dsps"]))),
                macro("ImplDspsAvailable", grouped(available(util["dsps"]))),
                macro("ImplBrams", grouped(used(util["block_ram_tiles"]))),
                macro(
                    "ImplBramsAvailable",
                    grouped(available(util["block_ram_tiles"])),
                ),
                macro("ImplIobs", grouped(used(util["bonded_iob"]))),
                macro(
                    "TimingStatus", "MET" if timing["timing_met"] else "VIOLATED"
                ),
                macro("WnsNs", f"{float(timing['worst_negative_slack_ns']):.3f}"),
                macro(
                    "CriticalDelayNs",
                    f"{float(timing.get('critical_data_path_delay_ns', 0.0)):.3f}",
                ),
                macro(
                    "VivadoFmaxMHz",
                    f"{float(timing['estimated_fmax_mhz']):.2f}",
                ),
                macro(
                    "TransformsPerSecond",
                    grouped(
                        int(
                            round(
                                float(
                                    derived.get(
                                        "transforms_per_second_at_estimated_fmax",
                                        0.0,
                                    )
                                )
                            )
                        )
                    ),
                ),
                macro(
                    "ComplexSamplesPerSecond",
                    f"{float(derived.get('complex_samples_per_second_at_estimated_fmax', 0.0)) / 1e6:.3f}",
                ),
                macro(
                    "VivadoTotalPowerW",
                    (
                        f"{float(power['total_on_chip_power_w']):.3f}"
                        if power.get("total_on_chip_power_w") is not None
                        else "--"
                    ),
                ),
                macro("VivadoPowerSource", tex_text(power_source)),
                macro(
                    "VivadoPowerConfidence",
                    tex_text(str(power.get("confidence_level", "not recorded"))),
                ),
                macro(
                    "VivadoPowerMatchedPercent",
                    f"{float(power.get('activity_net_match_percent', 0.0)):.1f}",
                ),
                macro(
                    "VivadoPowerMatchedNets",
                    grouped(int(power.get("activity_nets_matched", 0))),
                ),
                macro(
                    "VivadoPowerTotalNets",
                    grouped(int(power.get("activity_nets_total", 0))),
                ),
                macro(
                    "PostSynthFrames",
                    grouped(int(vivado["post_synthesis_simulation"]["frames"])),
                ),
                macro(
                    "PostSynthMismatches",
                    grouped(int(vivado["post_synthesis_simulation"]["mismatches"])),
                ),
                macro(
                    "PostImplFrames",
                    grouped(
                        int(vivado["post_implementation_timing_simulation"]["frames"])
                    ),
                ),
                macro(
                    "PostImplMismatches",
                    grouped(
                        int(
                            vivado["post_implementation_timing_simulation"][
                                "mismatches"
                            ]
                        )
                    ),
                ),
            ]
        )
    else:
        for name in (
            "SynthLuts",
            "SynthRegisters",
            "SynthDsps",
            "SynthBrams",
            "BaselineSynthLuts",
            "BaselineSynthRegisters",
            "BaselineSynthDsps",
            "BaselineSynthBrams",
            "ImplLuts",
            "ImplLutsAvailable",
            "ImplRegisters",
            "ImplRegistersAvailable",
            "ImplDsps",
            "ImplDspsAvailable",
            "ImplBrams",
            "ImplBramsAvailable",
            "ImplIobs",
            "WnsNs",
            "CriticalDelayNs",
            "VivadoFmaxMHz",
            "TransformsPerSecond",
            "ComplexSamplesPerSecond",
            "VivadoTotalPowerW",
            "VivadoPowerSource",
            "VivadoPowerConfidence",
            "VivadoPowerMatchedPercent",
            "VivadoPowerMatchedNets",
            "VivadoPowerTotalNets",
            "PostSynthFrames",
            "PostSynthMismatches",
            "PostImplFrames",
            "PostImplMismatches",
        ):
            lines.append(macro(name, "--"))
        lines.append(macro("TimingStatus", "NOT EXECUTED"))

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--require-vivado", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    content = render(manifest, args.require_vivado)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(
        f"generated={OUTPUT_PATH.relative_to(ROOT)} "
        f"vivado_status={manifest['vivado']['status']}"
    )


if __name__ == "__main__":
    main()
